import "katex/dist/katex.min.css"
import "normalize.css/normalize.css"
import "prism-solarized-dark/prism-solarizeddark.css"
import "prismjs/plugins/command-line/prism-command-line.css"
import "prismjs/plugins/line-numbers/prism-line-numbers.css"
import "./src/components/index.css"
